services:
  web:
    image: php:8.2-apache
    container_name: magd_web
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      IONCUBE_LOADER: "enabled"
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mysql:8
    container_name: magd_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magddb
      MYSQL_USER: magduser
      MYSQL_PASSWORD: magdpass
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
