services:
  web:
    image: php:8.2-apache
    container_name: magd_web
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      IONCUBE_LOADER: "enabled"
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID}:${GID}" # Run container as your user
    command: >
      sh -c "chown -R ${UID}:www-data /var/www/html/src &&
        find /var/www/html/src -type f -exec chmod 664 {} \; &&
        find /var/www/html/src -type d -exec chmod 775 {} \; &&
        apache2-foreground"

  db:
    image: mariadb:10.1
    container_name: magd_db
    restart: always
    environment:
      TZ: "Europe/Berlin"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magd
      MYSQL_USER: magduser
      MYSQL_PASSWORD: magdpass
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
    driver: local
